version: 2.1
jobs:
  build:
    docker:
      - image: nginx
    steps:
      - slack/notify:
          color: '#42e2f4'
          mentions: 'advaitkukade@gmail.com'
          message: This is a custom message notification.
          webhook: webhook
orbs:
  slack: circle/slack@3.4.0
version: 2.1
workflows:
  workflow_2:
    jobs:
      - build
