version: 2.1
jobs:
  build:
    docker:
      - image: 'circleci/node:10'
    steps:
      - run: echo "hello world"
    parallelism: 2
      
workflows:
  workflow_1:
    jobs:
      - build:
        
