version: 2.1
jobs:
  build:
    docker:
      - image: 'circleci/node:10'
    steps:
      - run: echo "Password - pass@123" >> file1.txt
      - run: echo "File Created Successfully with some data in it. "
workflows:
  workflow_1:
    jobs:
      - build
        
