version: 2
jobs:
  build:
    docker: 
      - image: nginx:latest 
      - image: advaitkukade/html:v2.0
    steps:
    - checkout
    - run: ls -al
workflows:
  version: 2 
  build_one:
    jobs:
      - build
    
