version: 2.1
jobs:
  build:
    docker:
      - image: ubuntu
    steps:
      #- run: apt-get update && apt install curl
      - slack/notify:
          color: '#42e2f4'
          mentions: 'advaitkukade@gmail.com'
          message: This is a custom message notification.
          webhook: www.gmail.com
orbs:
  slack: circleci/slack@3.4.0
workflows:
  workflow_2:
    jobs:
      - build
